import pandas as pd
import numpy as np
import matplotlib
matplotlib.use('Agg')  
import matplotlib.pyplot as plt
import seaborn as sns
from statsmodels.stats.outliers_influence import variance_inflation_factor
from statsmodels.tools.tools import add_constant
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import MinMaxScaler

# ─── Load data generated by A.1 ───
df = pd.read_csv('train_dataset.csv')

# ─── All 6 electrical features for VIF/correlation analysis ───
all_features      = ['Ia', 'Ib', 'Ic', 'Va', 'Vb', 'Vc']
selected_features = ['Ia', 'Ib', 'Ic', 'Va']  

X = df[all_features]
y = df['Fault_Type']

# ─── Correlation matrix ───
corr_matrix = X.corr(method='pearson').round(4)

# ─── VIF ───
X_const = add_constant(X)
vif = []
for i in range(1, X_const.shape[1]):
    try:
        v = variance_inflation_factor(X_const.values, i)
    except Exception:
        v = float('inf')
    vif.append(round(v, 2) if v != float('inf') else '∞')

# ─── RF importance  ───
scaler   = MinMaxScaler()
X_scaled = scaler.fit_transform(X)

rf = RandomForestClassifier(
    n_estimators=100, max_depth=10,
    random_state=42, n_jobs=-1
)
rf.fit(X_scaled, y)
rf_importances = (rf.feature_importances_ * 100).round(1)

# ─── Max absolute correlation ───
max_corr = [corr_matrix[col].drop(col).abs().max().round(4)
            for col in all_features]

# ─── Summary table ───
table = pd.DataFrame({
    'Feature'         : all_features,
    'RF_Importance_%' : rf_importances,
    'VIF'             : vif,
    'Max_Abs_Corr'    : max_corr,
    'Selected'        : ['Yes' if f in selected_features else 'No'
                         for f in all_features]
})
print("\n=== FEATURE ANALYSIS TABLE ===")
print(table.to_string(index=False))

# ─── Heatmap with VIF overlay on diagonal ───
plt.figure(figsize=(12, 10))
ax = sns.heatmap(
    corr_matrix, annot=True, fmt=".4f", cmap="RdBu_r",
    vmin=-1, vmax=1, linewidths=0.5, linecolor='white',
    cbar_kws={"shrink": 0.8}
)

for i, feat in enumerate(all_features):
    vif_val = table['VIF'].iloc[i]
    ax.text(i + 0.5, i + 0.5,
            f"VIF\n{vif_val}",
            ha='center', va='center',
            fontsize=11, fontweight='bold',
            bbox=dict(boxstyle="square,pad=0.5",
                      facecolor='white', edgecolor='white', alpha=1))

plt.title("Correlation Heatmap with VIF Overlaid on Diagonal",
          fontsize=16, pad=20)
plt.xticks(rotation=45, ha='right')
plt.yticks(rotation=0)
plt.tight_layout()
plt.savefig("correlation_heatmap_with_vif_overlay.png", dpi=300,
            bbox_inches='tight')
print("\n✅ Heatmap saved as: correlation_heatmap_with_vif_overlay.png")
plt.close()